sam2_checkpoint_path = "checkpoints/sam2.1_hiera_large.pt"
model_cfg_path = "configs/sam2.1/sam2.1_hiera_l.yaml"
con_frame_idx = 0  # the frame index we interact with
obj_id = 1  # give a unique id to each object we interact with (it can be any integers)
raw_data_dir = "raw_datasets/BrainTumorMRI" # for dcm files.
train_data_folder = "jpg_datasets/train/data/"
train_gt_folder = "jpg_datasets/test/gt/"
test_data_folder = "jpg_datasets/test/data/"
test_gt_folder = "jpg_datasets/test/gt/"